[tox]
envlist = copying,{py310,py313,py314}-{lint,tests,cli,checksetup}
skip_missing_interpreters = True

[testenv]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
deps=
    -rtests_utils/test-requirements.txt
    checksetup: {[testenv:checksetup]deps}
commands=
    tests:      {[testenv:tests]commands}
    lint:       {[testenv:lint]commands}
    cli:        {[testenv:cli]commands}
    checksetup: {[testenv:checksetup]commands}
    coverage:   {[testenv:coverage]commands}

[testenv:tests]
commands=
    pytest

[testenv:lint]
commands=
    ruff check iotlabsshcli
    ruff format --check iotlabsshcli
    isort --check-only iotlabsshcli
    pylint iotlabsshcli

[testenv:copying]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands=
    bash tests_utils/check_license.sh

[testenv:cli]
allowlist_externals =
    /bin/bash
    /usr/bin/bash
commands=
    bash -exc "open-a8-cli --help >/dev/null"
    bash -exc "iotlab-ssh --help > /dev/null"

[testenv:checksetup]
deps =
    build
    twine
skip_install = True
usedevelop = False
commands =
    python -m build --outdir {envtmpdir}/dist
    twine check {envtmpdir}/dist/*

[testenv:coverage]
passenv = CI TRAVIS TRAVIS_*
commands = codecov -e TOXENV
